### ISSUE TITLE
token too long error

### ISSUE THREAD

**Issue by Paalon** [semilin/genkey#15]
I'm using Japanese text corpus, but Japanese typing doesn't use space between words so get `token too long` error even for ordinal inputs for example:

```txt
nettoekisupandobukkuwoyomutamenosohutoueanokodouguissikiha,senkyu-hyakukyu-ju-rokuheiseihatitosinonatuni,makkubantouindo-zubannnosouhougasoroimasu.
```

```
Reading...
panic: bufio.Scanner: token too long

goroutine 1 [running]:
main.GetTextData({0x7ff7bfeff55e, 0x2f})
	/home/semi/code/genkey/text.go:118 +0x6d4
main.main()
	/home/semi/code/genkey/main.go:184 +0x14c5
```

**Comment by Paalon** [comment]
Sorry, that input doesn't give error, but other long text corpus that has no new line and few spaces gives the error.
